INSERT INTO tb_website (LINK) VALUES ('http://transparenciadamantina.sp.gov.br/');
INSERT INTO tb_website (LINK) VALUES ('https://www.adolfo.sp.gov.br/');
INSERT INTO tb_website (LINK) VALUES ('https://aguai.sp.gov.br/home/portal-da-transparecia/');
INSERT INTO tb_website (LINK) VALUES ('http://www.portaltransparencia.gov.br/localidades/3500402-aguas-da-prata');
INSERT INTO tb_website (LINK) VALUES ('https://www.aguasdelindoia.sp.gov.br/cria/transparencia');
INSERT INTO tb_website (LINK) VALUES ('https://www.aguasdesantabarbara.sp.gov.br/');
INSERT INTO tb_website (LINK) VALUES ('https://www.aguasdesaopedro.sp.gov.br/');
INSERT INTO tb_website (LINK) VALUES ('http://s2.asp.srv.br/etransparencia.pm.agudos.sp/servlet/portal');
INSERT INTO tb_website (LINK) VALUES ('http://www.alambari.sp.gov.br/');
INSERT INTO tb_website (LINK) VALUES ('https://www.alfredomarcondes.sp.gov.br/');


INSERT INTO tb_county (COUNTY_NAME,MAYOR_NAME,POPULATION,WEBSITE_ID) VALUES ('Adamantina', 'Marcio Cardim', 464450,1);
INSERT INTO tb_county (COUNTY_NAME,MAYOR_NAME,POPULATION,WEBSITE_ID) VALUES ('Adolfo', 'Izael Fernandes', 32000,2);
INSERT INTO tb_county (COUNTY_NAME,MAYOR_NAME,POPULATION,WEBSITE_ID) VALUES ('Aguaí', 'Alexandre Araújo', 18000,3);
INSERT INTO tb_county (COUNTY_NAME,MAYOR_NAME,POPULATION,WEBSITE_ID) VALUES ('Águas da Prata', 'Regina',5000,4);
INSERT INTO tb_county (COUNTY_NAME,MAYOR_NAME,POPULATION,WEBSITE_ID) VALUES ('Águas de Lindóia', 'Gil Helou',1000,5);
INSERT INTO tb_county (COUNTY_NAME,MAYOR_NAME,POPULATION,WEBSITE_ID) VALUES ('Águas de Santa Bárbara', 'Aroldo',3000,6);
INSERT INTO tb_county (COUNTY_NAME,MAYOR_NAME,POPULATION,WEBSITE_ID) VALUES ('Águas de São Pedro', 'João Victor Barboza',32500,7);
INSERT INTO tb_county (COUNTY_NAME,MAYOR_NAME,POPULATION,WEBSITE_ID) VALUES ('Agudos', 'Fernando Octaviani', 80000,8);
INSERT INTO tb_county (COUNTY_NAME,MAYOR_NAME,POPULATION,WEBSITE_ID) VALUES ('Alambari', 'João Paulo Carioca',15000,9);
INSERT INTO tb_county (COUNTY_NAME,MAYOR_NAME,POPULATION,WEBSITE_ID) VALUES ('Alfredo Marcondes', 'Celso Pirani', 12000,10);

INSERT INTO tb_income (APPLICATION, BUDGETED_VALUE, COLLECTED_VALUE, DESCRIPTION, FONT, INCOME_DATE, TYPE, COUNTY_ID) VALUES('EDUCAÇÃO',1000000,900000,'INVESTIMENTO EM EDUCAÇÃO','GOVERNO','2020-07-14T10:00:00Z',1,1);
INSERT INTO tb_income (APPLICATION, BUDGETED_VALUE, COLLECTED_VALUE, DESCRIPTION, FONT, INCOME_DATE, TYPE, COUNTY_ID) VALUES('CULTURA',2000000,50000,'INVESTIMENTO EM CULTURA','GOVERNO','2020-07-14T10:00:00Z',2,2);
INSERT INTO tb_income (APPLICATION, BUDGETED_VALUE, COLLECTED_VALUE, DESCRIPTION, FONT, INCOME_DATE, TYPE, COUNTY_ID) VALUES('LAZER',3000000,400000,'INVESTIMENTO EM LAZER','GOVERNO','2020-07-14T10:00:00Z',1,3);
INSERT INTO tb_income (APPLICATION, BUDGETED_VALUE, COLLECTED_VALUE, DESCRIPTION, FONT, INCOME_DATE, TYPE, COUNTY_ID) VALUES('ENTRETENIMENTO',4000000,200000,'INVESTIMENTO EM ENTRETENIMENTO','GOVERNO','2020-07-14T10:00:00Z',1,4);
INSERT INTO tb_income (APPLICATION, BUDGETED_VALUE, COLLECTED_VALUE, DESCRIPTION, FONT, INCOME_DATE, TYPE, COUNTY_ID) VALUES('MÚSICA',5000000,100000,'INVESTIMENTO EM MÚSICA','GOVERNO','2020-07-14T10:00:00Z',2,5);
INSERT INTO tb_income (APPLICATION, BUDGETED_VALUE, COLLECTED_VALUE, DESCRIPTION, FONT, INCOME_DATE, TYPE, COUNTY_ID) VALUES('ESPORTES',6000000,600000,'INVESTIMENTO EM ESPORTES','GOVERNO','2020-07-14T10:00:00Z',1,6);
INSERT INTO tb_income (APPLICATION, BUDGETED_VALUE, COLLECTED_VALUE, DESCRIPTION, FONT, INCOME_DATE, TYPE, COUNTY_ID) VALUES('CAUSAS SOCIAIS',7000000,500000,'INVESTIMENTO EM CAUSAS SOCIAIS','GOVERNO','2020-07-14T10:00:00Z',2,7);
INSERT INTO tb_income (APPLICATION, BUDGETED_VALUE, COLLECTED_VALUE, DESCRIPTION, FONT, INCOME_DATE, TYPE, COUNTY_ID) VALUES('QUESTÕES SOCIOAMBIENTAIS',8000000,550000,'INVESTIMENTOS EM QUESTÕES SOCIOAMBIENTAIS','GOVERNO','2020-07-14T10:00:00Z',1,8);
INSERT INTO tb_income (APPLICATION, BUDGETED_VALUE, COLLECTED_VALUE, DESCRIPTION, FONT, INCOME_DATE, TYPE, COUNTY_ID) VALUES('SANEAMENTO BÁSICO',9000000,250000,'INVESTIMENTO EM SANEAMENTO BÁSICO ','GOVERNO','2020-07-14T10:00:00Z',1,9);
INSERT INTO tb_income (APPLICATION, BUDGETED_VALUE, COLLECTED_VALUE, DESCRIPTION, FONT, INCOME_DATE, TYPE, COUNTY_ID) VALUES('CONSTRUÇÕES CIVIS',10000000,200000,'INVESTIMENTO EM CONSTRUÇÃO CIVIL','GOVERNO','2020-07-14T10:00:00Z',1,10);

CREATE VIEW VW_COUNTY AS SELECT C.ID,C.COUNTY_NAME, C.POPULATION, W.LINK, I.APPLICATION ,I.BUDGETED_VALUE, I.COLLECTED_VALUE, I.INCOME_DATE, I.TYPE FROM TB_COUNTY AS C INNER JOIN TB_WEBSITE AS W ON C.WEBSITE_ID = W.ID INNER JOIN TB_INCOME AS I ON I.COUNTY_ID = C.ID;


